---
- name: Deploy httpd.conf
  template:
    src: httpd.conf
    dest: /etc/
    owner: root 
    group: wheel
    mode: 0644
    backup: no
  notify:
    - restart httpd

- name: Ensure httpd is started and enabled
  service:
    name: httpd
    state: started
    enabled: yes

- name: Download and refresh certs
  cron:
    name: "Download current certs"
    hour: "0"
    minute: "0"
    job: "/usr/sbin/acme-client www.{{ ansible_domain }} && rcctl reload httpd && logger 'Updated www.{{ ansible_domain }} ssl certs'"
    user: root
