---
- name: Install vnstat
  openbsd_pkg:
    name: vnstat
    state: present

- name: Deploy vnstat.conf 
  template:
    src: vnstat.conf.j2
    dest: /etc/vnstat.conf
    owner: root 
    group: wheel 
    mode: 0644
    backup: yes
  notify:
    - restart vnstatd

