---
- name: Install go
  openbsd_pkg:
    name: go
    state: present

- name: Create git directory
  file:
    path: /root/git
    state: directory
    owner: admin
    group: admins
    mode: 0755

- name: Download go-ethereum source
  git:
    repo: https://github.com/ethereum/go-ethereum.git
    dest: /root/git/go-ethereum

- name: Correct line to include openbsd
  lineinfile:
    path: /root/git/go-ethereum/vendor/github.com/Azure/azure-storage-blob-go/2018-03-28/azblob/zc_mmf_unix.go
    state: present
    regexp: ^//
    line: // +build linux darwin freebsd openbsd

- name: Correct line to ensure allowance is at least 512
  lineinfile:
    path: /root/git/go-ethereum/cmd/geth/main.go
    state: present
    regexp: allowance := int(mem.Total / 1024 / 1024 / 3)
    line: allowance := 256

- name: Make geth
  make:
    chdir: /root/git/go-ethereum
    target: geth

- name: Install geth binary
  shell: cp /root/git/go-ethereum/build/bin/geth /usr/local/bin/
