---
- hosts: 127.0.0.1
  roles:
    - { role: pf, tags: pf }
    - { role: users, tags: users }
    - { role: system, tags: system }
    - { role: wireguard-binaries, tags: wireguard-binaries }
    - { role: wireguard-configs, tags: wireguard-configs }
    - { role: unbound, tags: unbound }
    - { role: vnstatd, tags: vnstatd }
    - { role: ifstated, tags: ifstated }
    - { role: x11vnc, tags: x11vnc }
