---
- hosts: 127.0.0.1
  roles:
    - { role: users, tags: users }
    - { role: system, tags: system }
    - { role: wireguard-pf, tags: wireguard-pf }
    - { role: wireguard-binaries, tags: wireguard-binaries }
    - { role: wireguard-configs, tags: wireguard-configs }
    - { role: l2tp-ipsec, tags: l2tp-ipsec }
    - { role: unbound, tags: unbound }
    - { role: vnstatd, tags: vnstatd }
    - { role: ifstated, tags: ifstated }
    - { role: x11vnc, tags: x11vnc }
    - { role: httpd_basic, tags: httpd_basic }
    - { role: httpd_tls, tags: httpd_tls }
    - { role: desktop, tags: desktop }
    - { role: ethereum, tags: ethereum }
    - { role: zabbix-postgresql, tags: zabbix-postgresql }
    - { role: zabbix-web, tags: zabbix-web }
    - { role: aria, tags: aria }
    - { role: reboot, tags: reboot }
