---
- name: Deploy unbound config
  template:
    src: unbound.conf.j2
    dest: /var/unbound/etc/unbound.conf
    owner: root
    group: wheel
    mode: 0644
    backup: yes
  notify:
    - restart unbound

- name: Create unbound log folder
  file:
    path: /var/unbound/log
    owner: root
    group: wheel
    state: directory
    mode: 0755

- name: Create unbound log
  copy:
    content: ""
    dest: /var/unbound/log/unbound.log
    force: no
    owner: _unbound
    group: wheel
    mode: 0644
  notify:
    - restart unbound

- name: Check for root.key for dnssec
  shell: "ls /var/unbound/db/root.key"
  register: rootkey
  ignore_errors: true
  changed_when: false
  check_mode: no

- name: Create unbound root.key
  shell: unbound-anchor -a "/var/unbound/db/root.key"
  args:
    creates: /var/unbound/db/root.key
  register: createrootkey
  changed_when: false
  failed_when: createrootkey.rc == 2
  notify:
    - restart unbound

- name: Create unbound control certs
  shell: unbound-control-setup
  args:
    creates: /var/unbound/etc/unbound_control.key
  changed_when: false

- name: Ensure unbound is started and enabled
  service:
    name: unbound
    state: started
    enabled: yes
