---
- name: Fail if required vars are absent
  fail:
    msg: "Missing required var {{ item }}"
  when:
    - vars[item] is not defined
  with_items:
    - domain

- name: Install required packages
  openbsd_pkg:
    name: ['dkimproxy','dovecot']
    state: present

- name: "Template out {{ item }}"
  template:
    src: "{{ item }}"
    dest: "/etc/{{ item }}"
    owner: root
    group: wheel
    mode: 0600
  with_items:
    - pf.conf
    - httpd.conf
    - acme-client.conf

- name: Create dkim private key
  shell: openssl genrsa -out /etc/ssl/private/dkim.key 1024
  changed_when: true
  failed_when: false
  args:
    creates: /etc/ssl/private/dkim.key

- name: Create dkim public key
  shell: openssl rsa -in /etc/ssl/private/dkim.key -pubout -out /etc/ssl/dkim_public.key
  failed_when: false
  changed_when: true
  args:
    creates: /etc/ssl/dkim_public.key

- name: Create acme-client keys
  shell: "acme-client -ADv {{ domain }}"
  failed_when: false
  changed_when: true
  args:
    creates: "/etc/ssl/private/mail.{{ domain }}.com.key"
  
- name: Create users and domains files
  template:
    src: "{{ item }}"
    dest: "/etc/mail/{{ item }}"
  with_items:
    - users
    - domains

- name: Create aliases.db
  shell: newaliases
  failed_when: false
  changed_when: true
  args:
    creates: /etc/mail/aliases.db
  
- name: Template out smtpd.conf
  template:
    src: smtpd.conf
    dest: /etc/mail/smtpd.conf
    owner: root
    group: wheel
    mode: 0644

- name: Set permissions for /var/mail to allow dovecot to create emails under subdirectories
  file:
    path: /var/mail
    owner: root
    group: _dovecot
    mode: 0775

- name: Create /var/mail/dovecot directory for storing emails
  file:
    path: /var/mail/dovecot
    state: directory
    owner: root
    group: _dovecot
    mode: 0775

- name: Template dovecot.conf
  template:
    src: dovecot.conf
    dest: /etc/dovecot/dovecot.conf
    owner: root
    group: wheel
    mode: 0644

- name: "Template out dovecot config {{ item }}"
  template:
    src: "{{ item }}"
    dest: "/etc/dovecot/conf.d/{{ item }}"
    owner: root
    group: wheel
    mode: 0600
  with_items:
    - 10-auth.conf
    - 10-mail.conf
    - 10-ssl.conf
    - 15-mailboxes.conf

- name: Create mailname file
  copy: 
    content="{{ domain}}.com" 
    dest=/etc/mail/mailname

