- name: Install required packages
  openbsd_pkg:
    name: ['aria2']
    state: present

- name: Create www data directory
  file:
    path: /var/www/htdocs/data
    state: directory
    mode: 0755
    owner: admin
    group: www

- name: Add aria alias to .kshrc
  blockinfile:
    path: /home/admin/.kshrc
    block: |
        alias aria='aria2c -d /var/www/htdocs/data -V -u 5 --seed-time=0'

        function get_links {
            for folder in $(ls /var/www/htdocs/data)
            do
                for file in $(ls /var/www/htdocs/data/$folder)
                do
                    echo http://$(ifconfig egress | grep inet | awk '{print $2}')/${folder}$file
                done
            done
        }

- name: Template out httpd.conf
  template: 
    src: httpd.conf
    dest: /etc/httpd.conf
    owner: root
    group: wheel

- name: Start and enable httpd
  service:
    name: httpd
    state: started
    enabled: true
