---
- name: install zabbix server
  openbsd_pkg:
    name: ['zabbix-server-4.0.0-pgsql','zabbix-web-4.0.0p0','postgresql-server-11.2p1','py3-pip','php-pgsql-7.1.28','php-curl-7.1.28','php-intl-7.1.28','php-pdo_pgsql-7.1.28']
    state: present

- name: Template out login.conf
  template:
    src: login.conf
    dest: /etc/login.conf
    owner: root
    group: wheel
    mode: 0644

- name: Configure sysctl kern.seminfo.semmni
  sysctl:
    name: kern.seminfo.semmni
    value: 30
    sysctl_set: yes
    state: present
    reload: yes

- name: Configure sysctl kern.seminfo.semmns
  sysctl:
    name: kern.seminfo.semmns
    value: 120
    sysctl_set: yes
    state: present
    reload: yes

- name: Configure sysctl kern.shminfo.shmall
  sysctl:
    name: sysctl kern.shminfo.shmall
    value: 524288
    sysctl_set: yes
    state: present
    reload: yes

- name: Install required python modules
  pip:
    name: psycopg2
    executable: pip3.6

# This part still is asking for the password when running the playbook
- name: Initialize postgresql
  shell: echo -e "root11\nroot11" | initdb -D /var/postgresql/data -U postgres -A trust -W
  args:
    creates: /var/postgresql/data
  become: yes
  become_user: _postgresql
  become_method: su

- name: Start postgresql
  service:
    name: postgresql
    state: started
    enabled: yes

- name: Create zabbix user, set password, grant privs
  postgresql_user:
    name: zabbix
    password: zabbix
    role_attr_flags: CREATEDB,NOSUPERUSER,NOCREATEROLE
  become: yes
  become_user: _postgresql
  become_method: su

- name: Create zabbix database
  postgresql_db:
    name: zabbix
    owner: zabbix
  become: yes
  become_user: _postgresql
  become_method: su
    
- name: Initialize schema
  shell: cat /usr/local/share/zabbix/schema/postgresql/schema.sql | psql -U zabbix zabbix
  become: yes
  become_user: _postgresql
  become_method: su
  
- name: Initialize images
  shell: cat /usr/local/share/zabbix/schema/postgresql/images.sql | psql -U zabbix zabbix
  become: yes
  become_user: _postgresql
  become_method: su
  
- name: Initialize data
  shell: cat /usr/local/share/zabbix/schema/postgresql/data.sql | psql -U zabbix zabbix
  become: yes
  become_user: _postgresql
  become_method: su

- name: Add DBPassword into zabbix_server.conf
  lineinfile:
    path: /etc/zabbix/zabbix_server.conf
    regexp: '^DBPassword='
    line: DBPassword=zabbix

- name: Copy over php modules
  shell: cp /etc/php-7.1.sample/* /etc/php-7.1/

- name: Start zabbix_server
  service:
    name: zabbix_server
    state: started
    enabled: yes

- name: Start php service
  service: 
    name: php71_fpm
    state: started
    enabled: yes
 
- name: Template out httpd.conf
  template:
    src: httpd.conf
    dest: /etc/httpd.conf
    owner: root
    group: wheel
    mode: 0644

- name: Start php71_fpm
  service: 
    name: php71_fpm
    state: started
    enabled: yes

- name: Start httpd
  service: 
    name: httpd
    state: started
    enabled: yes
