---
- name: install zabbix server
  openbsd_pkg:
    name: ['zabbix-server-4.0.0-pgsql','zabbix-web-4.0.0p0','postgresql-server-11.2p1','py3-pip']
    state: present

- name: Template out login.conf
  template:
    src: login.conf
    dest: /etc/login.conf
    owner: root
    group: wheel
    mode: 0644

- name: Configure sysctl kern.seminfo.semmni
  sysctl:
    name: kern.seminfo.semmni
    value: 30
    sysctl_set: yes
    state: present
    reload: yes

- name: Configure sysctl kern.seminfo.semmns
  sysctl:
    name: kern.seminfo.semmns
    value: 120
    sysctl_set: yes
    state: present
    reload: yes

- name: Configure sysctl kern.shminfo.shmall
  sysctl:
    name: sysctl kern.shminfo.shmall
    value: 524288
    sysctl_set: yes
    state: present
    reload: yes

- name: Install required python modules
  pip:
    name: psycopg2
    executable: pip3.6

- name: Initialize postgresql
  shell: echo -e "root11\nroot11" | initdb -D /var/postgresql/data -U postgres -A trust -W
  args:
    creates: /var/postgresql/data
  become: yes
  become_user: _postgresql
  become_method: su

- name: Start postgresql
  service:
    name: postgresql
    state: started
    enabled: yes

- name: Create zabbix user, set password, grant privs
  postgresql_user:
    name: zabbix
    password: zabbix
    role_attr_flags: CREATEDB,NOSUPERUSER,NOCREATEROLE
  become: yes
  become_user: _postgresql
  become_method: su

- name: Create zabbix database
  postgresql_db:
    name: zabbix
    owner: zabbix
  become: yes
  become_user: _postgresql
  become_method: su
    
