---
- name : Get current wireguard version
  shell: "echo \"{{ distros.stdout }}\" | grep upstream.*go | cut -f 3"
  register: wireguard_version
  ignore_errors: true
  changed_when: false

- name: Download WireGuard-go source
  get_url:
    url: "https://git.zx2c4.com/wireguard-go/snapshot/wireguard-go-{{ wireguard_version.stdout }}.tar.xz"
    dest: /tmp/

- name: Extract WireGuard-go source
  unarchive:
    src: "/tmp/wireguard-go-{{ wireguard_version.stdout }}.tar.xz"
    dest: /usr/src/wireguard/

- name: Prepare WireGuard-go Makefile for OpenBSD
  shell: "cd /usr/src/wireguard && sed -i 's/install -v/install/g;s/@install/install/g' \"wireguard-go-{{ wireguard_version.stdout }}/Makefile\""
  changed_when: false

- name: Build wireguard-go
  shell: "cd /usr/src/wireguard && gmake -j$(sysctl -n hw.ncpu) -C \"wireguard-go-{{ wireguard_version.stdout }}\" PREFIX=/usr/local"
  changed_when: false

- name: Check if new wireguard-go binary is different than installed version
  shell: "test $(md5 -q /usr/src/wireguard/wireguard-go-{{ wireguard_version.stdout }}/wireguard-go) == $(md5 -q /usr/local/bin/wireguard-go)"
  register: wireguardgo_md5
  ignore_errors: true
  changed_when: false

- name: Install wireguard-go
  shell: "cd /usr/src/wireguard && gmake -j$(sysctl -n hw.ncpu) -C \"wireguard-go-{{ wireguard_version.stdout }}\" PREFIX=/usr/local install"
  changed_when: false
  when: wireguardgo_md5.rc != 0
